services:
#    chicago_bike.example:
#        class: ChicagoBikeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    postgis_subscriber:
        class: Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber
        tags:
            - {name: doctrine.event_subscriber}
