<?php

namespace ChicagoBikeBundle\Repository;

/**
 * BikeRelocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BikeRelocationRepository extends \Doctrine\ORM\EntityRepository
{
}
